# Generated by Django 3.2.12 on 2022-04-04 12:35

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.TextBlock()), ('page', wagtail.core.blocks.PageChooserBlock())], blank=True, null=True),
        ),
    ]
